CREATE TABLE PUBLIC.USER
(
    user_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_name VARCHAR2 NOT NULL
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT unique_user_id UNIQUE (user_id);

CREATE TABLE PUBLIC.ROLE
(
    role_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    role_name VARCHAR2 NOT NULL,
    user_id INT NOT NULL
);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT unique_role_id UNIQUE (role_id);



