CREATE TABLE PROJECT
(
    PROJECT_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PROJECT_NAME VARCHAR(255)
);

CREATE TABLE ROLE
(
    USER_ROLE_ID BIGINT PRIMARY KEY NOT NULL,
    ROLE_NAME VARCHAR(255)
);

CREATE TABLE TASK
(
    TASK_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCR VARCHAR(255),
    PROJECT_ID BIGINT,
    USER_ID BIGINT,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

CREATE TABLE USER
(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ENABLED INTEGER,
    PASSWORD VARCHAR(255),
    USER_NAME VARCHAR(255)
);

CREATE TABLE USERS_ROLES
(
    USER_ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ROLE_ID, USER_ID),
    FOREIGN KEY (USER_ROLE_ID) REFERENCES ROLE (USER_ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);



