INSERT INTO PROJECT VALUES (1, 'Project1');
INSERT INTO PROJECT VALUES (2, 'Project2');
INSERT INTO PROJECT VALUES (3, 'Project3');

INSERT INTO USER VALUES (1, '1', '1', 'man1');
INSERT INTO USER VALUES (2, '1', '1', 'dev1');
INSERT INTO USER VALUES (3, '1', '1', 'dev2');